### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by anissen** [kevinresol/docker-haxe#1]
Thanks for providing an up-to-date haxe docker. It would be really nice with a small guide or examples of how to use the container for building for different targets with haxe, running haxelib and neko and so on.

**Comment by kevinresol** [comment]
There really isn't much to say about it. It is just standard docker image.

You can run the container directly:
`docker run -ti -v /host/directory:/container/directory kevinresol/haxe bash`
And then from within the containier bash, run:
`cd /container/directory && haxe build.hxml`
That should build the things inside your host's directory. (Not tested but that should work in theory)

Or you can use it in docker-based CI such as GitLab CI, then you can call `haxe build.hxml` from the CI script. (This is how I am using the image myself)

**Comment by anissen** [comment]
Okay, thanks for the elaboration.
